import {Product} from "../interfaces/common.interface";

export const initialProducts: Product[] = [
  {
    id: 1,
    name: 'Laptop ACER Aspire 7 A715-42G-R05G',
    image: '/assets/images/products/acer-aspire-7.webp',
    price: 17990000,
    category: 'laptop',
    description: 'Laptop ACER Aspire 7 A715-42G-R05G là một chiếc laptop mạnh mẽ, thiết kế để đáp ứng nhu cầu về hiệu suất và năng suất. Máy được trang bị bộ vi xử lý AMD Ryzen 5 5500U, 8GB RAM và ổ cứng SSD 512GB giúp thực hiện nhiều tác vụ cùng lúc một cách nhanh chóng và hiệu quả. Laptop đi kèm với hệ điều hành Windows 11 đã được cài đặt sẵn, mang lại một giao diện người dùng thân thiện và an toàn. Với thiết kế mỏng nhẹ và màn hình chất lượng cao, Laptop ACER Aspire 7 là lựa chọn hoàn hảo cho công việc và giải trí.',
  },
  {
    id: 2,
    name: 'Smartphone Samsung Galaxy S21',
    image: '/assets/images/products/samsung-galaxy-s21.jpg',
    price: 19990000,
    category: 'smartphone',
    description: 'Điện thoại thông minh Samsung Galaxy S21 là một sản phẩm hàng đầu với hiệu năng mạnh mẽ và tính năng đột phá. Với màn hình Dynamic AMOLED 2X rực rỡ, camera chất lượng cao và khả năng xử lý mượt mà, Samsung Galaxy S21 mang đến trải nghiệm điện thoại vượt trội. Với tính năng thông minh và kết nối tốc độ cao, bạn có thể làm mọi việc từ trò chuyện video đến làm việc di động một cách dễ dàng.',
  },
  {
    id: 3,
    name: 'Smart TV LG OLED C1 Series',
    image: '/assets/images/products/lg-oled-c1.jpg',
    price: 35990000,
    category: 'smartTV',
    description: 'Smart TV LG OLED C1 Series là một chiếc TV thông minh hàng đầu với công nghệ màn hình OLED tiên tiến. Với màu sắc rực rỡ, độ tương phản cao và góc nhìn rộng, LG OLED C1 Series mang đến trải nghiệm hình ảnh sống động và chân thực. Bạn có thể tận hưởng nội dung giải trí phong phú với hệ điều hành webOS thông minh của LG, bạn có thể truy cập các ứng dụng phổ biến như Netflix, YouTube và Disney+ trực tiếp trên TV của mình. Ngoài ra, LG OLED C1 Series còn hỗ trợ công nghệ âm thanh Dolby Atmos, mang đến âm thanh mô phỏng không gian sống động. Với thiết kế hiện đại và tính năng thông minh, Smart TV LG OLED C1 Series là lựa chọn hoàn hảo cho việc giải trí tại nhà.',
  },
  {
    id: 4,
    name: 'Headphones Sony WH-1000XM4',
    image: '/assets/images/products/sony-wh-1000xm4.jpg',
    price: 4990000,
    category: 'headphone',
    description: 'Tai nghe Sony WH-1000XM4 là một trong những tai nghe chống ồn hàng đầu trên thị trường. Với công nghệ chống ồn hiện đại và âm thanh chất lượng cao, tai nghe này mang đến trải nghiệm nghe nhạc tuyệt vời. Được trang bị Bluetooth và tính năng điều khiển cảm ứng, bạn có thể dễ dàng kết nối và điều chỉnh âm lượng. Thiết kế nhẹ nhàng và êm ái, tai nghe Sony WH-1000XM4 là sự lựa chọn lý tưởng cho việc thưởng thức âm nhạc và trải nghiệm giải trí cá nhân.',
  },
  {
    id: 5,
    name: 'Laptop Dell XPS 13',
    image: '/assets/images/products/dell-xps-13.jpg',
    price: 23990000,
    category: 'laptop',
    description: 'Laptop Dell XPS 13 là một chiếc laptop siêu mỏng và nhẹ với hiệu năng mạnh mẽ. Với màn hình InfinityEdge viền siêu mỏng, bộ vi xử lý Intel Core i7 và ổ cứng SSD 512GB, Dell XPS 13 mang đến trải nghiệm làm việc và giải trí tuyệt vời. Thiết kế sang trọng cùng pin lâu và tính di động cao, đây là một lựa chọn lý tưởng cho những người luôn di chuyển.',
  },
  {
    id: 6,
    name: 'Smartphone iPhone 13 Pro',
    image: '/assets/images/products/iphone-13-pro.jpg',
    price: 27990000,
    category: 'smartphone',
    description: 'iPhone 13 Pro là một chiếc smartphone hàng đầu của Apple với hiệu năng mạnh mẽ và camera chất lượng cao. Với màn hình Super Retina XDR, bộ vi xử lý A15 Bionic và hệ thống camera ba ống kính, iPhone 13 Pro mang đến trải nghiệm hoàn hảo cho việc chụp ảnh và quay video. Ngoài ra, nó cũng hỗ trợ công nghệ 5G, Face ID và tính năng chống nước. Được thiết kế sang trọng và có sẵn trong các phiên bản màu sắc đẹp, iPhone 13 Pro là một lựa chọn đáng xem xét.',
  },
  {
    id: 7,
    name: 'Smart TV Sony BRAVIA XR A80J',
    image: '/assets/images/products/sony-bravia-a80j.jpg',
    price: 49990000,
    category: 'smartTV',
    description: 'Smart TV Sony BRAVIA XR A80J là một chiếc TV thông minh hàng đầu với công nghệ màn hình OLED và âm thanh đỉnh cao. Với công nghệ trí tuệ nhân tạo Cognitive Processor XR, màn hình OLED chất lượng cao và âm thanh Dolby Atmos, Sony BRAVIA XR A80J mang đến trải nghiệm hình ảnh và âm thanh sống động. Ngoài ra, nó cũng có tính năng điều khiển giọng nói và tương thích với các dịch vụ streaming phổ biến. Với thiết kế tinh tế và khả năng kết nối đa dạng, đây là một lựa chọn...',
  },
  {
    id: 8,
    name: 'Laptop HP Spectre x360',
    image: '/assets/images/products/hp-spectre-x360.webp',
    price: 31990000,
    category: 'laptop',
    description: 'Laptop HP Spectre x360 là một chiếc laptop 2 trong 1 với thiết kế sang trọng và hiệu năng mạnh mẽ. Với màn hình cảm ứng xoay 360 độ, bộ vi xử lý Intel Core i7 và ổ cứng SSD 1TB, HP Spectre x360 mang đến sự linh hoạt và hiệu suất tốt cho việc làm việc và giải trí. Laptop còn đi kèm với bút cảm ứng và tích hợp tính năng bảo mật vân tay, giúp bạn dễ dàng và an toàn trong việc truy cập và sử dụng.',
  },
  {
    id: 9,
    name: 'Smartphone Google Pixel 6 Pro',
    image: '/assets/images/products/google-pixel-6-pro.webp',
    price: 22990000,
    category: 'smartphone',
    description: 'Google Pixel 6 Pro là một chiếc smartphone đáng chú ý với hệ điều hành Android và tính năng camera vượt trội. Với chip Snapdragon 895, màn hình OLED 6.7 inch và hệ thống camera đa ống kính, Google Pixel 6 Pro mang đến trải nghiệm chụp ảnh và quay video chất lượng cao. Ngoài ra, nó cũng hỗ trợ công nghệ 5G, tích hợp Google Assistant và bảo mật tiên tiến. Với thiết kế đẹp và giao diện người dùng mượt mà, Pixel 6 Pro là một sự lựa chọn hấp dẫn cho người dùng Android.',
  },
  {
    id: 10,
    name: 'Smart TV Samsung QLED Q90T',
    image: '/assets/images/products/samsung-qled-q90t.webp',
    price: 54990000,
    category: 'smartTV',
    description: 'Smart TV Samsung QLED Q90T là một chiếc TV cao cấp với công nghệ màn hình QLED và hiệu suất ấn tượng. Với độ phân giải 4K, hệ điều hành Tizen thông minh và công nghệ Quantum HDR, Samsung QLED Q90T mang đến hình ảnh sắc nét, màu sắc chân thực và độ tương phản tốt. Ngoài ra, nó còn hỗ trợ âm thanh nổi của công nghệ Object Tracking Sound+ và tính năng điều khiển giọng nói. Với thiết kế siêu mỏng và viền...',
  },
  {
    id: 11,
    name: 'Headphones Bose QuietComfort 35 II',
    image: '/assets/images/products/bose-quietcomfort-35-ii.jpg',
    price: 2999000,
    category: 'headphone',
    description: 'Tai nghe Bose QuietComfort 35 II là một trong những tai nghe chống ồn hàng đầu trên thị trường. Với công nghệ chống ồn hoàn hảo, âm thanh mạnh mẽ và thoải mái, Bose QuietComfort 35 II mang đến trải nghiệm nghe nhạc tuyệt vời và giảm tiếng ồn xung quanh. Nó còn có tính năng kết nối Bluetooth và điều khiển thông qua ứng dụng điện thoại di động, cho phép bạn dễ dàng thay đổi nhạc và điều chỉnh âm lượng.',
  },
  {
    id: 12,
    name: 'Laptop ASUS ROG Zephyrus G14',
    image: '/assets/images/products/asus-rog-zephyrus-g14.jpg',
    price: 29990000,
    category: 'laptop',
    description: 'Laptop ASUS ROG Zephyrus G14 là một chiếc laptop chơi game mạnh mẽ và di động. Với bộ vi xử lý AMD Ryzen 9 5900HS, đồ họa NVIDIA GeForce RTX 3060 và màn hình 14 inch, ASUS ROG Zephyrus G14 mang đến hiệu suất tuyệt vời cho trải nghiệm chơi game mượt mà. Ngoài ra, nó còn có thiết kế mỏng nhẹ, bàn phím có đèn nền và pin lâu dùng. Đây là một lựa chọn tuyệt vời cho những người yêu thích chơi game trên di động.',
  },
  {
    id: 13,
    name: 'Smartphone OnePlus 9 Pro',
    image: '/assets/images/products/oneplus-9-pro.jpg',
    price: 18990000,
    category: 'smartphone',
    description: 'OnePlus 9 Pro là một chiếc smartphone cao cấp với hiệu năng mạnh mẽ và camera chất lượng cao. Với chip Snapdragon 888, màn hình Fluid AMOLED 6.7 inch và hệ thống camera Hasselblad, OnePlus 9 Pro mang đến trải nghiệm chụp ảnh và quay video chất lượng cao. Ngoài ra, nó còn hỗ trợ công nghệ 5G, tích hợp OxygenOS mượt mà và sạc nhanh Warp Charge. Với thiết kế đẹp và hiệu năng ấn tượng, OnePlus 9 Pro là một sự lựa chọn tốt cho người dùng Android.',
  },
  {
    id: 14,
    name: 'Smart TV LG NanoCell NANO90',
    image: '/assets/images/products/lg-nanocell-nano90.jpg',
    price: 45990000,
    category: 'smartTV',
    description: 'Smart TV LG NanoCell NANO90 là một chiếc TV cao cấp với công nghệ NanoCell và tính năng thông minh. Với độ phân giải 4K, màn hình IPS và công nghệ Full Array Dimming, LG NanoCell NANO90 mang đến hình ảnh rõ nét, màu sắc chân thực và độ tương phản tốt. Ngoài ra, nó còn hỗ trợ âm thanh Dolby Atmos và công nghệ AI ThinQ, cho phép bạn điều khiển TV bằng giọng nói và tương tác với trợ lý ảo. Với thiết kế đẹp và khả năng kết nối đa dạng, đây là một lựa chọn tuyệt vời cho việc giải trí tại nhà.',
  },
  {
    id: 15,
    name: 'Headphones Sony WH-1000XM4',
    image: '/assets/images/products/sony-wh-1000xm4.jpg',
    price: 3499000,
    category: 'headphone',
    description: 'Tai nghe Sony WH-1000XM4 là một trong những tai nghe chống ồn hàng đầu trên thị trường. Với công nghệ chống ồn tuyệt vời, âm thanh cao cấp và thiết kế thoải mái, Sony WH-1000XM4 mang đến trải nghiệm nghe nhạc và cuộc sống hàng ngày tuyệt vời. Nó cung cấp tính năng kết nối Bluetooth, điều khiển cảm ứng và thời lượng pin lên đến 30 giờ. Tai nghe cũng được trang bị công nghệ LDAC cho truyền phát âm thanh chất lượng cao.',
  },
  {
    id: 16,
    name: 'Laptop Lenovo ThinkPad X1 Carbon',
    image: '/assets/images/products/lenovo-thinkpad-x1-carbon.jpg',
    price: 31990000,
    category: 'laptop',
    description: 'Laptop Lenovo ThinkPad X1 Carbon là một chiếc laptop doanh nghiệp mỏng nhẹ với hiệu năng mạnh mẽ. Với bộ vi xử lý Intel Core i7, RAM 16GB và ổ cứng SSD 1TB, Lenovo ThinkPad X1 Carbon mang đến sự linh hoạt và đáng tin cậy cho công việc hàng ngày. Thiết kế bền bỉ với vỏ hợp kim magiê, bàn phím chống tràn và tính năng ...',
  },
  {
    id: 17,
    name: 'Smartphone Samsung Galaxy S21 Ultra',
    image: '/assets/images/products/samsung-galaxy-s21-ultra.jpg',
    price: 28990000,
    category: 'smartphone',
    description: 'Samsung Galaxy S21 Ultra là một chiếc smartphone cao cấp với hiệu năng mạnh mẽ và camera vượt trội. Với chip Exynos 2100 (hoặc Snapdragon 888), màn hình Dynamic AMOLED 6.8 inch và hệ thống camera đa ống kính, Galaxy S21 Ultra mang đến trải nghiệm chụp ảnh và quay video chất lượng cao. Ngoài ra, nó còn hỗ trợ công nghệ 5G, bút S Pen và tích hợp giao diện người dùng One UI mượt mà. Với thiết kế đẹp và tính năng hàng đầu, Galaxy S21 Ultra là một sự lựa chọn ấn tượng trong dòng điện thoại Samsung.',
  },
  {
    id: 18,
    name: 'Smart TV TCL 6-Series',
    image: '/assets/images/products/tcl-6-series.jpg',
    price: 6499000,
    category: 'smartTV',
    description: 'Smart TV TCL 6-Series là một chiếc TV giá rẻ với chất lượng hình ảnh 4K HDR và tính năng thông minh. Với công nghệ QLED và hệ điều hành Roku TV, TCL 6-Series mang đến màu sắc chân thực, độ tương phản cao và truy cập đa dạng vào các ứng dụng phổ biến. Nó cũng hỗ trợ âm thanh Dolby Atmos và có thiết kế mỏng viền siêu mỏng. Đây là một sự lựa chọn phù hợp cho những người muốn có một chiếc TV 4K giá trị.',
  },
  {
    id: 19,
    name: 'Headphones JBL Quantum 800',
    image: '/assets/images/products/jbl-quantum-800.webp',
    price: 3499000,
    category: 'headphone',
    description: 'Tai nghe JBL Quantum 800 là một chiếc tai nghe chơi game chất lượng cao với âm thanh vòm mạnh mẽ. Với công nghệ ANC (chống ồn hoạt động), âm thanh JBL QuantumSOUND Signature và tích hợp microphone, JBL Quantum 800 mang đến trải nghiệm chơi game sống động và chất lượng cao. Nó còn hỗ trợ kết nối không dây Bluetooth và thời lượng pin lên đến 14 giờ. Tai nghe cũng có thiết kế thoải mái với mút tai nghe...',
  },
  {
    id: 20,
    name: 'Laptop Dell XPS 13',
    image: '/assets/images/products/dell-xps-13.jpg',
    price: 24990000,
    category: 'laptop',
    description: 'Laptop Dell XPS 13 là một chiếc laptop mỏng nhẹ và mạnh mẽ với hiệu suất ấn tượng. Với bộ vi xử lý Intel Core i7, RAM 16GB và ổ cứng SSD 512GB, Dell XPS 13 mang đến sự linh hoạt và đáng tin cậy cho công việc và giải trí. Nó có màn hình InfinityEdge 13.3 inch với độ phân giải cao và viền mỏng, tạo ra trải nghiệm hình ảnh tuyệt vời. Laptop cũng có thiết kế sang trọng với vỏ nhôm và bàn phím chiếu sáng.',
  },
  {
    id: 21,
    name: 'Smartphone Apple iPhone 13 Pro',
    image: '/assets/images/products/iphone-13-pro.jpg',
    price: 29990000,
    category: 'smartphone',
    description: 'Apple iPhone 13 Pro là một chiếc smartphone cao cấp với hiệu năng mạnh mẽ và camera đa ống kính. Với chip A15 Bionic, màn hình Super Retina XDR 6.1 inch và hệ thống camera Pro, iPhone 13 Pro mang đến trải nghiệm chụp ảnh và quay video chất lượng cao. Ngoài ra, nó còn hỗ trợ công nghệ 5G, tích hợp Face ID và có thiết kế sang trọng từ khung thép không gỉ và mặt kính Ceramic Shield. Với hiệu năng ấn tượng và tính năng hàng đầu, iPhone 13 Pro là một trong những lựa chọn hàng đầu trong dòng điện thoại di động.',
  },
  {
    id: 22,
    name: 'Smart TV Sony BRAVIA A80J',
    image: '/assets/images/products/sony-bravia-a80j.jpg',
    price: 69990000,
    category: 'smartTV',
    description: 'Smart TV Sony BRAVIA A80J là một chiếc TV cao cấp với công nghệ màn hình OLED và hệ điều hành Android TV. Với độ phân giải 4K HDR, công nghệ X1 Ultimate Picture Processor và âm thanh Dolby Atmos, Sony BRAVIA A80J mang đến hình ảnh chân thực và âm thanh mạnh mẽ. Nó còn hỗ trợ công nghệ Acoustic Surface Audio+ để tạo ra âm thanh tự nhiên đến từ bề mặt màn hình. Với thiết kế sang trọng và khả năng tương tác thông...',
  },
  {
    id: 23,
    name: 'Headphones Sennheiser HD 660 S',
    image: '/assets/images/products/sennheiser-hd-660s.jpg',
    price: 3999000,
    category: 'headphone',
    description: 'Tai nghe Sennheiser HD 660 S là một tai nghe hi-fi cao cấp với âm thanh tự nhiên và chi tiết. Với driver động cơ độc quyền và công nghệ Sennheiser E.A.R. (Eargonomic Acoustic Refinement), HD 660 S mang đến trải nghiệm nghe nhạc chất lượng cao với dải tần rộng và độ tách biệt tốt. Nó có thiết kế mở, cung cấp không gian âm thanh rộng và thoải mái trong suốt thời gian sử dụng. Đây là một sự lựa chọn tuyệt vời cho những người yêu âm nhạc và đam mê chi tiết âm thanh.',
  },
  {
    id: 24,
    name: 'Laptop HP Spectre x360',
    image: '/assets/images/products/hp-spectre-x360.webp',
    price: 24990000,
    category: 'laptop',
    description: 'Laptop HP Spectre x360 là một chiếc laptop 2 trong 1 với thiết kế sang trọng và hiệu suất ấn tượng. Với bộ vi xử lý Intel Core i7, RAM 16GB và ổ cứng SSD 1TB, HP Spectre x360 mang đến sự linh hoạt và đa nhiệm cho công việc và giải trí. Nó có màn hình cảm ứng 13.3 inch với độ phân giải cao và khả năng xoay 360 độ, cho phép bạn sử dụng như một chiếc laptop hoặc máy tính bảng. Laptop cũng được trang bị bút stylus và có thời lượng pin lên đến 22 giờ.',
  },
  {
    id: 25,
    name: 'Smartphone Google Pixel 6 Pro',
    image: '/assets/images/products/google-pixel-6-pro.webp',
    price: 23990000,
    category: 'smartphone',
    description: 'Google Pixel 6 Pro là một chiếc smartphone cao cấp với hiệu năng mạnh mẽ và camera chất lượng cao. Với chip Google Tensor, màn hình pOLED 6.7 inch và hệ thống camera đa ống kính, Pixel 6 Pro mang đến trải nghiệm chụp ảnh và quay video chất lượng cao. Ngoài ra, nó còn hỗ trợ công nghệ 5G, tích hợp Google Assistant và có thiết kế độc đáo từ...',
  },
  {
    id: 26,
    name: 'Smart TV Samsung The Frame',
    image: '/assets/images/products/samsung-the-frame.jpg',
    price: 18990000,
    category: 'smartTV',
    description: 'Smart TV Samsung The Frame là một chiếc TV độc đáo với thiết kế giống một bức tranh treo trên tường. Với công nghệ QLED, độ phân giải 4K UHD và chế độ Art Mode, The Frame không chỉ là một chiếc TV thông thường mà còn là một tác phẩm nghệ thuật hiện đại. Nó cung cấp khả năng tương thích với nhiều khung ảnh và tác phẩm nghệ thuật từ bộ sưu tập Art Store của Samsung. Đây là một sự lựa chọn phù hợp cho những người yêu nghệ thuật và muốn kết hợp giải trí với trang trí nội thất.',
  },
  {
    id: 27,
    name: 'Headphones Bose QuietComfort 35 II',
    image: '/assets/images/products/bose-quietcomfort-35-ii.jpg',
    price: 2499000,
    category: 'headphone',
    description: 'Tai nghe Bose QuietComfort 35 II là một chiếc tai nghe chống ồn hàng đầu với âm thanh vòm tuyệt vời. Với công nghệ Noise Cancelling, âm thanh Balanced và tích hợp trợ lý ảo Google Assistant, QuietComfort 35 II mang đến trải nghiệm nghe nhạc tĩnh lặng và thoải mái. Nó cung cấp kết nối không dây Bluetooth và thời lượng pin lên đến 20 giờ. Tai nghe có thiết kế nhẹ, êm tai và có thể gập lại để dễ dàng mang theo khi di chuyển.',
  },
  {
    id: 28,
    name: 'Laptop ASUS ROG Zephyrus G14',
    image: '/assets/images/products/asus-rog-zephyrus-g14.jpg',
    price: 34990000,
    category: 'laptop',
    description: 'Laptop ASUS ROG Zephyrus G14 là một chiếc laptop gaming mạnh mẽ với hiệu suất ấn tượng. Với bộ vi xử lý AMD Ryzen 9, GPU NVIDIA GeForce RTX và RAM 16GB, Zephyrus G14 mang đến trải nghiệm chơi game mượt mà và đáng tin cậy. Nó có màn hình 14 inch với độ phân giải cao và tốc độ làm mới 120Hz, cung cấp hình ảnh sắc nét và mượt mà. Laptop cũng được trang bị bàn phím chiếu sáng, âm thanh Dolby Atmos và...',
  },
  {
    id: 29,
    name: 'Smartphone OnePlus 9 Pro',
    image: '/assets/images/products/oneplus-9-pro.jpg',
    price: 21990000,
    category: 'smartphone',
    description: 'OnePlus 9 Pro là một chiếc smartphone cao cấp với hiệu năng mạnh mẽ và camera đa ống kính. Với chip Qualcomm Snapdragon 888, màn hình Fluid AMOLED 6.7 inch và hệ thống camera Hasselblad, OnePlus 9 Pro mang đến trải nghiệm chụp ảnh và quay video chất lượng cao. Nó cung cấp khả năng sạc nhanh Warp Charge 65T và sạc không dây Warp Charge 50, giúp sạc nhanh và tiện lợi. Thiết kế sang trọng và hiệu năng ấn tượng của OnePlus 9 Pro làm cho nó trở thành một trong những lựa chọn hàng đầu trong thị trường smartphone.',
  },
  {
    id: 30,
    name: 'Headphones Sony WH-1000XM4',
    image: '/assets/images/products/sony-wh-1000xm4.jpg',
    price: 3999000,
    category: 'headphone',
    description: 'Tai nghe Sony WH-1000XM4 là một chiếc tai nghe chống ồn cao cấp với âm thanh vượt trội và tính năng thông minh. Với công nghệ Noise Cancelling, âm thanh Hi-Res và chất lượng âm thanh 360 Reality Audio, WH-1000XM4 mang đến trải nghiệm nghe nhạc tuyệt vời. Nó cung cấp kết nối không dây Bluetooth và thời lượng pin lên đến 30 giờ. Tai nghe còn có điều khiển cảm ứng thông minh và tích hợp trợ lý ảo Google Assistant và Alexa. Thiết kế thoải mái và êm tai của WH-1000XM4 cho phép bạn thưởng thức âm nhạc trong suốt thời gian dài.',
  },
];
