export interface Product {
  id: string,
  name: string,
  image: string,
  price: string,
  discount: string,
  moreImages: string[],
  brand: string,
  sku: string,
  category: string,
  processor?: string,
  display?: string,
  ram?: string,
  graphics?: string,
  storage?: string,
  operatingSystem?: string,
  battery?: string,
  weight?: string,
  resolution?: string,
  smartFeatures?: string[],
  hdrSupport?: string,
  connectivity?: string[],
  type?: string,
  wireless?: boolean,
  noiseCancellation?: boolean,
}
